article:
  head: |
    \documentclass{article}

    % jats2tex requirements
    @@requirements

    \begin{document}

    @@heads

    \maketitle

    @@bodies

    \end{document}

article-title:
  head: |
    \title{@@children}

contrib: "@@children"

back: ""

name: |
  @@lua(
  s = find "surname"
  g = find "given-names"
  return s .. ", " .. g
  )@@

contrib-group:
  head: |

    \author{@@lua(
    return table.concat(elements(), '\\and ')
    )@@}

break: "\n"

code: |
  \code{@@children}

codebold: |
  \code{@@children}

kwd: |
  \textit{@@children}

p: |

  @@lua(
    align_to_ragged = {
      ["center"] = "Center",
      ["left"] = "FlushLeft",
      ["right"] = "FlushRight",
    }

    if attr('align') == nil then
      return children()
    end

    env = align_to_ragged[attr('align')]
    if env == nil then
      return children()
    end

    return string.format([[
      \begin{%s}
      %s
      \end{%s}
    ]], env, children(), env)
  )@@

pub-date: |
  \date{@@lua(return find "year")@@}{@@lua(return find "month")@@}{@@lua(return find "day")@@}

abstract: |
  @@lua(
    if attr('xml:lang') == 'en' then
      return "\\abstract{" .. children() .. "}"
    end

    return ""
  )@@

volume: |
  \newcommand{\volume}{@@children}

numero: |
  \newcommand{\numero}{@@children}

fpage: |
  \newcommand{\fpage}{@@children}

lpage: |
  \newcommand{\lpage}{@@children}

copyright-statement: |
  \newcommand{\copyrightstatement}{@@children}

copyright-year: |
  \newcommand{\copyrightyear}{@@children}

b: |
  \textbf{@@children}

sup: |
  \textsuperscript{th}

sec: |
  \section{@@lua(return find('title'))@@}
  @@lua(return find('p'))@@
