article:
  head: |
    \documentclass{article}

    % jats2tex requirements
    @@requirements

    \begin{document}
    @@heads

    \maketitle

    @@bodies
    \end{document}

article-title:
  head: |
    \title{@@children}

# contrib-group:
#   head: |
#     \author{
#       @@(
#         intercalate "\and" children
#       )@@
#     }

b: |
  \textbf{@@children}
