article:
  head: |
    \documentclass{article}

    % jats2tex requirements
    @@requirements

    \begin{document}

    @@heads

    \maketitle

    @@bodies

    \end{document}

article-title:
  head: |
    \title{@@children}

contrib: "@@children"

back: ""

name: |
  @@(
  findChildren "surname"
  )@@, @@(
  findChildren "given-names"
  )@@

contrib-group:
  head: |
    \author{
      @@(
        intercalate (raw "\\and") =<< elements context
      )@@
    }

break: "\n"

code: |
  \code{@@children}

kwd: |
  \textit{@@children}

# p: |
#   @@(alignToRagged)@@
#   @@children
#   @@(alignToRaggedEnv)@@

b: |
  \textbf{@@children}
