name: jats2tex
version: '0.5.0.0'
author: Pedro Tacla Yamada
maintainer: yamada@beijaflor.io
category: Language
description: jats2tex converts JATS-XML to LaTeX
synopsis: jats2tex converts JATS-XML to LaTeX
license: AllRightsReserved
extra-source-files:
- README.md

dependencies:
- base >=4 && <5
- xml
- mtl
- containers
- HaTeX
- HaXml
- text
- optparse-applicative
- bytestring
- text-icu
- executable-hash
- cabal-file-th
- wreq
- lens
- lens-aeson
- vector
- aeson
- directory
- temporary
- filepath
- open-browser
- polyparse
- unordered-containers
- yaml
- shakespeare
- cryptohash
# - wxHaskell

library:
  source-dirs:
  - src

executables:
  jats2tex:
    main: Main.hs
    source-dirs:
    - ./bin
    dependencies:
    - jats2tex

  jats2tex-web:
    main: JatexWeb.hs
    source-dirs:
    - ./bin
    dependencies:
    - jats2tex
    - yesod
    - Spock
    - hamlet
    - http-types
    - unordered-containers
    - aeson
    - shakespeare
    - blaze-html
    - here
    - wai-middleware-static

  jats2tex-remove-c-data:
    main: RemoveCData.hs
    source-dirs:
    - ./bin
    dependencies:
    - xml
    - jats2tex

  jats2tex-build-installer:
    main: Main.hs
    source-dirs:
    - ./bin/windows-installer
    dependencies:
    - nsis
    when:
      condition: 'os(windows)'
      then:
        buildable: true
      else:
        buildable: false

#tests:
  #hspec:
    #main: Spec.hs
    #source-dirs: test
    #dependencies:
    #- base
    #- hspec
    #- QuickCheck
    #- jats2tex
    #- here
