name: jats2tex
version: '0.3.2.0'
author: Pedro Tacla Yamada
maintainer: yamada@beijaflor.io
synopsis: jats2tex converts JATS-XML to LaTeX
license: AllRightsReserved
extra-source-files:
- README.md

dependencies:
- base >=4 && <5
- xml
- mtl
- containers
- HaTeX
- HaXml
- text
- optparse-applicative
- bytestring
- text-icu
- executable-hash
- cabal-file-th
- wreq
- lens
- lens-aeson
- vector
- aeson
- directory
- temporary
- filepath
- open-browser

library:
  source-dirs:
  - src

executables:
  jats2tex:
    main: Main.hs
    source-dirs:
    - ./bin
    dependencies:
    - jats2tex

  jats2tex-web:
    main: JatexWeb.hs
    source-dirs:
    - ./bin
    dependencies:
    - jats2tex
    - yesod
    - Spock
    - hamlet
    - http-types
    - unordered-containers
    - aeson
    - shakespeare
    - blaze-html
    - here
    - wai-middleware-static

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - hspec
    - QuickCheck
    - jats2tex
    - here
