flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ./jats2tex-web
extra-deps:
- digestive-functors-0.8.2.0
- digestive-functors-aeson-1.1.21
- hexpat-0.20.13
- hxt-expat-9.1.1
- hxt-xpath-9.1.2.2
- luautils-0.1.4
- raven-haskell-0.1.0.1
- th-utilities-0.2.0.1
- wreq-0.5.0.1
- yesod-auth-1.4.17.2
resolver: lts-8.0
