flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ./jats2tex-web
extra-deps:
- luautils-0.1.4
- wreq-0.5.0.1
- yesod-auth-1.4.17.2
- th-utilities-0.2.0.1
- digestive-functors-aeson-1.1.21
- digestive-functors-0.8.2.0
- hxt-xpath-9.1.2.2
resolver: lts-8.0
